export const PURCHASE_ITEM_API_BASE_URL = `/purchase-item`;
export const PURCHASE_ITEM_API_ENDPOINTS = {
  LIST: `${PURCHASE_ITEM_API_BASE_URL}/list`,
  LIST_ITEM_TYPES: `${PURCHASE_ITEM_API_BASE_URL}/list-types`,
  LIST_ITEM_UNITS: `${PURCHASE_ITEM_API_BASE_URL}/list-units`,
  LIST_ITEM_CATEGORIES: `${PURCHASE_ITEM_API_BASE_URL}/list-categories`,
  LIST_ITEM_BRANDS: `${PURCHASE_ITEM_API_BASE_URL}/list-brands`,
  TOTAL_PROJECT_PRICE: `${PURCHASE_ITEM_API_BASE_URL}/total-project-price`,
  SUMMARY: `${PURCHASE_ITEM_API_BASE_URL}/summary`,
};
